### ISSUE TITLE
Maybe scratch_file_dir fix for Windows

### ISSUE THREAD

**Issue by Jxstxs** [LintaoAmons/scratch.nvim#2]
Instead of `vim.env.HOME` I would suggest to use `vim.fn.stdpath()`, because of my Knowledge this is OS independent.

So I would write the scratch files to cache:

```lua
require("scratch").setup {
	scratch_file_dir = vim.fn.stdpath("cache") .. "/scratch.nvim"
}
```

On Linux it should give `~/.cache/nvim/scratch.nvim`

and on Windows I think something to `APPDATA`

**Comment by LintaoAmons** [comment]
Thx, I'm really don't familiar with nvim API, so the implementation is merely MVP, grab anything that I knew~ 

So really need more hints like this ~

**Comment by Jxstxs** [comment]
Feel free to ask when you need help! :smile:

**Comment by LintaoAmons** [comment]
> Feel free to ask when you need help! 😄

Nice ~~ And I have changed the default directory

**Comment by LintaoAmons** [comment]
But the separator `/`， is it valid for window? @Jxstxs

**Comment by Jxstxs** [comment]
with `vim.loop.os_uname().sysname` you can get the os type in nvim. Now you could write a function which returns the specific character for the os ( `/` or `\`)
