### ISSUE TITLE
enhancement: `CONFIG_FILE_FLAG_PATH` variable and `configFilePath` file should be removed

### ISSUE THREAD

**Issue by OliverChao** [LintaoAmons/scratch.nvim#26]
`CONFIG_FILE_FLAG_PATH` variable and `configFilePath` file is redundant.
While searching Scratch files using `ScratchOpen` or `ScrachOpenFzf`, `configFilePath` always exists but it should not.
Maybe  we can use `lua option` or `Env` var (`SCRATCH_CONFIG_FILE_PATH`). 

=======

Using `lua option` maybe one good idea, because this option is hardly be changed after `Scratch` start up.

**Comment by OliverChao** [comment]
Thanks for you reply. 
`CONFIG_FILE_FLAG_PATH` points to the configFilePath which only consists of the path of `scratch_config.json`.
If using lua option for example `scratch_config_file_path` (with one default value), we can just testify if the file exists.  
If exists, just read it. If not, `scratch.nvim` can create one. 

of course, This change can be merge in all-lua-options process.
Lua config (and https://github.com/LintaoAmons/scratch.nvim/issues/21) is worthy supporting although it works fine for me now.

**Comment by LintaoAmons** [comment]
already use config with lua
