### ISSUE TITLE
`ScratchWithName` does not allow to select type

### ISSUE THREAD

**Issue by januz** [LintaoAmons/scratch.nvim#32]
Just ran across your plugin and it looks great! I'm having the following issue though: When I use `ScratchWithName`, I can enter the name but I'm not offered the menu to select the file type. Is that the expected behavior?

**Comment by LintaoAmons** [comment]
Hi, you can type in any postfix when you write your filename

e.g.: `myfilename.md` will just create a file with `md` as it's postfix, then it should be a markdown file.

**Comment by januz** [comment]
Okay, that makes sense! Thank you
