### ISSUE TITLE
Help - Callback after scratch file created?

### ISSUE THREAD

**Issue by Ajaymamtora** [LintaoAmons/scratch.nvim#34]
I'm looking to create a scratch file in the middle of a shortcut that sets up a REPL. Is there any way for me to run code once the filetype has been selected from the new scratchfile select?

**Comment by Rizhiy** [comment]
The way I've done it is just to have an autocommand which is run for files in my scratch directory:
```lua
vim.api.nvim_create_autocmd({ "BufEnter" }, {
    pattern = "*/scratch.nvim/*",
    command = "Codi",
})
```

**Comment by Rizhiy** [comment]
You can prompt for confirmation inside the lua function? Or write a function which first creates a scratchpad using this plugin and then sets up whatever is required.

**Comment by LintaoAmons** [comment]
[41c2659](https://github.com/LintaoAmons/scratch.nvim/commit/41c2659a26d1a3954d1cc852473e8dfb24d3078b)

Implemented

**Comment by LintaoAmons** [comment]
can check it out and feel free to reopen it if it's not meet your usecase
