### ISSUE TITLE
怎么增加自己的配置呢

### ISSUE THREAD

**Issue by duanyongcheng77** [LintaoAmons/scratch.nvim#7]
```lua
["LintaoAmons/scratch.nvim"]={
	config = function()
		require("scratch").setup({
			filetypes = {"java"}
		})
	end,
},
```
在setup增加了自己的配置，但是似乎没有生效
```
{
  filetypes = { "json", "xml", "go", "lua", "js", "py", "sh", "md", "txt" },
  scratch_file_dir = "/Users/bary/.cache/nvim/scratch.nvim"
}
```

**Comment by LintaoAmons** [comment]
要在加载了插件之后，再去调用 setup 才行的样子～

不能直接在这里 config = ....

我也不知道为什么...

**Comment by xuzixx** [comment]
> 现在可以非常轻松地更改自己的配置了，通过 `ScratchEditConfig` 命令

~/.cache/nvim/scratch.nvim/config.json  新版本配置文件必须指定到这里是么？感觉这样不太友好对于用一个git 管理nvim 配置

**Comment by LintaoAmons** [comment]
OK~ 我想了个 enhance 的办法

**Comment by LintaoAmons** [comment]
@xuzixx I added a initProcess to allow user to decide where they want to put their configuration file~ Please try and feedback are welcome
