### ISSUE TITLE
Error when configuring the plugin

### ISSUE THREAD

**Issue by carlosflorencio** [LintaoAmons/scratch.nvim#9]
Hi, I was about to test the plugin but I'm getting the following error when running the config commands:

<img width="1221" alt="image" src="https://user-images.githubusercontent.com/1500881/235796321-60d64e97-d43d-402b-8c9b-76ae8c1540e8.png">

I'm in neovim 0.9.

**Comment by LintaoAmons** [comment]
OK，thx for your report, I will look into it soon

**Comment by LintaoAmons** [comment]
@carlosflorencio I fixed it, please try to update the plugin to latest version (v0.7.1)
